version: '3'

services:
  frontend:
    build:
      context: ./frontend
      # dockerfile: Dockerfile
    ports:
      - "5001:5001"
    volumes:
      - ./frontend:/app

  backend:
    build:
      context: ./backend
      # dockerfile: Dockerfile
    ports:
      - "5000:5000"
    volumes:
      - ./backend:/app
